pipeline {
  agent none
  stages {
    
    stage('Checkout') {
    agent any
           steps {
             checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Sachin-094/Jenkins-Zero-To-Hero']])
           }
         }
	 stage('Build') { 
	 agent any
	             steps {
		                     sh 'mvn -B -DskipTests clean package' 
		}

    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
